# emmet-vim
[[plugins]]
repository = 'mattn/emmet-vim'
on_ft = ['html', 'xhtml']
on_cmd = ['Emmet', 'EmmetInstall']
on_map = '<Plug>(emmet-'

# jedi-vim
[[plugins]]
repository = 'davidhalter/jedi-vim'
on_ft = 'python'
depends = 'davidhalter/jedi'

# neoinclude.vim
[[plugins]]
repository = 'Shougo/neoinclude.vim'
depends = 'Shougo/neocomplete.vim'
on_source = ['neocomplete.vim', 'deoplete.nvim']

# neosnippet-snippets
[[plugins]]
repository = 'Shougo/neosnippet-snippets'
on_source = 'neosnippet.vim'
depends = 'Shougo/neosnippet.vim'

# neosnippet.vim
[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends = 'Shougo/context_filetype.vim'
on_path = '.snip'
on_source = ['neocomplete.vim', 'deoplete.nvim', 'unite.vim']
on_cmd = 'NeoSnippetEdit'

# perlomni.vim
[[plugins]]
repository = 'c9s/perlomni.vim'
depends = 'neocomplete.vim'
on_ft = 'perl'

# vim-endwise
[[plugins]]
repository = 'tpope/vim-endwise'
on_ft = [
  'aspvbs', 'c', 'cpp', 'crystal', 'elixir', 'htmldjango', 'lua', 'matlab',
  'objc', 'ruby', 'sh', 'snippets', 'vb', 'vbnet', 'vim', 'xdefaults', 'zsh',
]

# vim-go
[[plugins]]
repository = 'fatih/vim-go'
on_ft = 'go'

# vim-go-impl
[[plugins]]
repository = 'rhysd/vim-go-impl'
on_ft = 'go'

# vim-nodejs-complete
[[plugins]]
repository = 'ahayman/vim-nodejs-complete'
on_ft = 'javascript'

# vim-smartchar
[[plugins]]
repository = 'kana/vim-smartchr'
on_ft = 'cpp'
