# AnsiEsc.vim
[[plugins]]
repository = 'AnsiEsc.vim'
on_cmd = 'AnsiEsc'

# dbext.vim
[[plugins]]
repository = 'dbext.vim'

# gist-vim
[[plugins]]
repository = 'mattn/gist-vim'
on_cmd = 'Gist'
depends = 'mattn/webapi-vim'

# neobundle.vim
[[plugins]]
repository = 'Shougo/neobundle.vim'
lazy = 0
depends = 'Shougo/vimproc.vim'
fetch = 1
on_unite = 'neobundle/update'

# securemodelines
[[plugins]]
repository = 'ciaranm/securemodelines'
lazy = 0

# sudo.vim
[[plugins]]
repository = 'sudo.vim'
on_cmd = ['SudoRead', 'SudoWrite']

# vimproc.vim
[[plugins]]
repository = 'Shougo/vimproc.vim'
lazy = 0

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin = 'make -f make_cygwin.mak'
  mac = 'make -f make_mac.mak'
  unix = 'make -f make_unix.mak'

# vimshell.vim
[[plugins]]
repository = 'Shougo/vimshell.vim'
depends = 'Shougo/vimproc.vim'

  [plugins.on_cmd]
  name = [
    'VimShell',
    'VimShellBufferDir',
    'VimShellCreate',
    'VimShellTab',
    'VimShellPop',
    'VimShellCurrentDir',
    'VimShellExecute',
    'VimShellInteractive',
    'VimShellTerminal',
    'VimShellSendString',
    'VimShellSendBuffer',
  ]
  complete = 'customlist,vimshell#complete'

# vim-abolish
[[plugins]]
repository = 'tpope/vim-abolish'
depends = 'tpope/vim-repeat'
on_cmd = ['Abolish', 'Subvert', 'S']
on_map = 'cr'

# vim-fugitive
[[plugins]]
repository = 'tpope/vim-fugitive'
augroup = 'fugitive'
on_cmd = [
  'Git', 'Git!', 'Gcd', 'Glcd', 'Gstatus', 'Gcommit', 'Gmerge', 'Gpull',
  'Gpush', 'Gfetch', 'Ggrep', 'Glgrep', 'Glog', 'Gllog', 'Gedit', 'Gsplit',
  'Gvsplit', 'Gtabedit', 'Gpedit', 'Gsplit!', 'Gvsplit!', 'Gtabedit!',
  'Gpedit!', 'Gread', 'Gread!', 'Gwrite', 'Gwrite', 'Gwq', 'Gwq!', 'Gdiff',
  'Gsdiff', 'Gvdiff', 'Gmove', 'Gremove', 'Gblame',
]

# vim-gista
[[plugins]]
repository = 'lambdalisue/vim-gista'
on_cmd = 'Gista'
on_unite = 'gista'

# vim-obsession
[[plugins]]
repository = 'tpope/vim-obsession'
lazy = 0
on_cmd = ['Obsession', 'Obsession!']

# vim-prettyprint
[[plugins]]
repository = 'thinca/vim-prettyprint'

  [plugins.on_cmd]
  name = ['PrettyPrint', 'PP']
  complete = 'expression'

# vim-ref
[[plugins]]
repository = 'thinca/vim-ref'
on_map = '<Plug>(ref-keyword)'
on_unite = 'ref'

  [plugins.on_cmd]
  name = 'Ref'
  complete = 'customlist,ref#complete'

# vim-repeat
[[plugins]]
repository = 'tpope/vim-repeat'
on_map = '.'
on_func = 'repeat#set'

# vim-speeddating
[[plugins]]
repository = 'tpope/vim-speeddating'
depends = 'tpope/vim-repeat'
on_map = ['<C-a>', '<C-x>']

# vinarise.vim
[[plugins]]
repository = 'Shougo/vinarise.vim'
vim_version = '7.3'

  [plugins.on_cmd]
  name = 'Vinarise'
  complete = 'file'

# webapi-vim
[[plugins]]
repository = 'mattn/webapi-vim'
